# Generated by Django 3.2.6 on 2022-03-18 18:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualidade', '0002_delete_fichacorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditor',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspecao',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='itemtabelaamostragem',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemtabelaamostragem',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='PlanoDeAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('Disposição', 'Disposição'), ('Corretiva', 'Corretiva'), ('Preventiva', 'Preventiva')], default='Disposição', max_length=10)),
                ('origem_acao', models.CharField(choices=[('Não Conformidade', 'Não Conformidade'), ('Melhoria', 'Melhoria'), ('Pesquisa', 'Pesquisa')], default='Não Conformidade', max_length=16)),
                ('tipo_referencia', models.CharField(choices=[('Ficha de Produção', 'Ficha de Produção')], default='Ficha de Produção', max_length=17)),
                ('referencia', models.CharField(max_length=20)),
                ('data_fim', models.DateField(blank=True, verbose_name='fim')),
                ('eficaz', models.BooleanField(blank=True)),
                ('evidencia', models.CharField(max_length=20)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualidade"."PlanoDeAcao',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_prazo', models.DateField(verbose_name='Prazo')),
                ('data_inicio', models.DateField(blank=True, verbose_name='inicio')),
                ('data_fim', models.DateField(blank=True, verbose_name='fim')),
                ('resposta', models.CharField(blank=True, max_length=100)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plano_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualidade.planodeacao')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AcaoResponsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qualidade"."Acao',
            },
        ),
    ]
