# Generated by Django 3.2.6 on 2022-03-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0003_auto_20220318_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeacao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='fim'),
        ),
    ]
