# Generated by Django 3.2.6 on 2022-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0004_alter_planodeacao_data_fim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planodeacao',
            name='eficaz',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planodeacao',
            name='evidencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
