# Generated by Django 3.2.6 on 2022-03-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0005_auto_20220319_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='fim'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='inicio'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='resposta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
