# Generated by Django 3.2.6 on 2022-03-20 18:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0008_auto_20220320_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualidadeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcp', jsonfield.fields.JSONField()),
            ],
        ),
    ]
