# Generated by Django 3.2.6 on 2021-12-22 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_abastecimento_corrida_despesaviagem_infracao_rastreio_seguro_veiculoabastecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='caminhao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorista',
            name='carro',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.motorista'),
        ),
    ]
