# Generated by Django 3.2.6 on 2021-12-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_auto_20211222_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='caminhao',
            field=models.BooleanField(default=False),
        ),
    ]
