# Generated by Django 3.2.6 on 2021-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_auto_20211227_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
