# Generated by Django 3.2.6 on 2022-03-10 23:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=20, null=True)),
                ('caminhao', models.BooleanField(default=False)),
                ('descricao', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ativo')),
            ],
            options={
                'db_table': 'frota"."veiculo',
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Manutençao', 'Manutenção'), ('Viagem', 'Viagem')], default='Viagem', max_length=40)),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('hora_inicial', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=40)),
                ('destino', models.CharField(max_length=250)),
                ('carga', models.CharField(blank=True, max_length=40)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('km_inicial', models.IntegerField(blank=True, null=True)),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('ajudante', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ajudante', to='core.pessoa')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('motorista', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pessoa')),
                ('motorista2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motorista2', to='core.pessoa')),
                ('veiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."viagem',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."seguro',
            },
        ),
        migrations.CreateModel(
            name='Rastreio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."rastreio',
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=20)),
                ('nome', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pessoa')),
            ],
            options={
                'db_table': 'frota"."motorista',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField(blank=True, null=True)),
                ('manutencao', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva')], max_length=40)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."manutencao',
            },
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('motivo', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."infracao',
            },
        ),
        migrations.CreateModel(
            name='FrotaPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_veiculo', models.BooleanField(default=True)),
                ('ver_manutencao', models.BooleanField(default=False)),
                ('ver_despesa', models.BooleanField(default=False)),
                ('ver_relatorio', models.BooleanField(default=False)),
                ('ver_carro', models.BooleanField(default=True)),
                ('ver_caminhao', models.BooleanField(default=True)),
                ('ver_abastecimento', models.BooleanField(default=True)),
                ('ver_viagemlist', models.BooleanField(default=True)),
                ('ver_empilhadeira', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frota"."frota_permissao',
            },
        ),
        migrations.CreateModel(
            name='DespesaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.viagem')),
            ],
            options={
                'db_table': 'frota"."despesa_viagem',
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interno', models.BooleanField(default=False)),
                ('combustivel', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina'), ('Álcool', 'Álcool')], max_length=40)),
                ('data', models.DateField()),
                ('valor_unitario', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('veiculo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."abastecimento',
            },
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(check=models.Q(('data_final__gte', django.db.models.expressions.F('data_inicial'))), name='datafinal_menor_datainicial'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(check=models.Q(('km_final__gt', django.db.models.expressions.F('km_inicial'))), name='kmfinal_menor_kminicial'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.UniqueConstraint(fields=('veiculo', 'data_inicial', 'hora_inicial'), name='Ja Reservado para esta data,verificar os horarios'),
        ),
    ]
