# Generated by Django 3.2.6 on 2022-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstoqueDiesel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('almoxarifado_id', models.IntegerField(db_column='almoxarifado_id')),
                ('produto_id', models.IntegerField(db_column='produto_id')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('quantidade', models.FloatField(db_column='quantidade')),
                ('valor_unico', models.FloatField(db_column='valor_unico')),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'souzacambos"."estoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemViagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'frota"."viagem_itens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimentacoes',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('estoque_id', models.IntegerField(db_column='estoque_id')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('tipo', models.CharField(db_column='tipo', max_length=1)),
                ('descricao', models.CharField(db_column='descricao', max_length=191)),
                ('quantidade', models.FloatField(db_column='quantidade')),
                ('saldo_anterior', models.FloatField(db_column='saldo_anterior')),
                ('saldo_atual', models.FloatField(db_column='saldo_atual')),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
            options={
                'db_table': 'souzacambos"."movimentacoes',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_unitario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
