# Generated by Django 3.2.6 on 2022-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_frotabot'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoViagem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('compras_pedido_id', models.IntegerField(db_column='compras_pedido_id', null=True)),
                ('data_prevista', models.DateField(db_column='data_prevista')),
                ('tipo', models.CharField(choices=[('1', 'Coleta'), ('2', 'Entrega'), ('3', 'Coleta Direta'), ('4', 'Entrada Direta')], db_column='tipo', max_length=1)),
                ('origem', models.CharField(choices=[('1', 'Compras'), ('2', 'Outros')], db_column='origem', max_length=1)),
                ('situacao', models.CharField(choices=[('1', 'Aguardando Atendimento'), ('2', 'Em Atendimento'), ('3', 'Finalizado')], db_column='situacao', max_length=1)),
                ('prioridade', models.CharField(choices=[('1', 'Normal'), ('2', 'Urgente')], db_column='prioridade', max_length=1)),
                ('peso', models.FloatField(db_column='peso')),
                ('data_solicitacao', models.DateTimeField(db_column='data_solicitacao')),
                ('data_atendimento', models.DateTimeField(db_column='data_atendimento', null=True)),
                ('data_finalizacao', models.DateTimeField(db_column='data_finalizacao', null=True)),
            ],
            options={
                'db_table': 'frota"."viagem_solicitacoes',
                'managed': False,
            },
        ),
    ]
