# Generated by Django 3.2.6 on 2021-12-21 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_viagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoAbastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combustivel', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."veiculo_abastecimento',
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."seguro',
            },
        ),
        migrations.CreateModel(
            name='Rastreio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."rastreio',
            },
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('motivo', models.CharField(max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."infracao',
            },
        ),
        migrations.CreateModel(
            name='DespesaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.viagem')),
            ],
            options={
                'db_table': 'frota"."despesa_viagem',
            },
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=40)),
                ('data', models.DateField()),
                ('km_inicial', models.IntegerField()),
                ('km_final', models.IntegerField()),
                ('observacao', models.CharField(blank=True, max_length=40)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."corrida',
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_unitario', models.FloatField()),
                ('quantidade', models.FloatField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculoabastecimento')),
            ],
            options={
                'db_table': 'frota"."abastecimento',
            },
        ),
    ]
