# Generated by Django 3.2.6 on 2022-03-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_solicitacaoviagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='frotabot',
            name='ver_logistica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frotabot',
            name='ver_relatorioveiculos',
            field=models.BooleanField(default=False),
        ),
    ]
