# Generated by Django 3.2.6 on 2022-03-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0006_auto_20220325_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleVisitantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=12)),
                ('hora_inicial', models.TimeField(blank=True, null=True)),
                ('hora_final', models.TimeField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'frota"."controle_visitante',
            },
        ),
        migrations.AddField(
            model_name='frotapermissao',
            name='ver_controlevisitas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frotapermissao',
            name='ver_solicitacao',
            field=models.BooleanField(default=False),
        ),
    ]
