# Generated by Django 3.2.6 on 2021-12-27 17:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frota', '0006_veiculo_caminhao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viagem',
            name='data',
        ),
        migrations.AddField(
            model_name='motorista',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='hora_inicial',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='carga',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='km_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota.motorista'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='origem',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='peso',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo'),
        ),
    ]
