# Generated by Django 3.2.6 on 2022-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_auto_20220328_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='abastecimento',
            name='responsavel',
            field=models.CharField(choices=[('JOAO LUIS SEMBOLONI', 'JOAO LUIS SEMBOLONI'), ('ANTONIO PEDRO DE ARAUJO FILHO', 'ANTONIO PEDRO DE ARAUJO FILHO'), ('ISAAC DA SILVA HERCULANO', 'ISAAC DA SILVA HERCULANO'), ('PAULO VITOR TAVEIRA', 'PAULO VITOR TAVEIRA'), ('JONATHAN CARVALHO XIMENES', 'JONATHAN CARVALHO XIMENES'), ('VALDIR DONIZETTI FERREIRA', 'VALDIR DONIZETTI FERREIRA'), ('LINDEMBERG RODRIGUES DA SILVA', 'LINDEMBERG RODRIGUES DA SILVA')], max_length=40, null=True),
        ),
    ]
