# Generated by Django 3.2.6 on 2021-12-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0008_alter_viagem_peso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corrida',
        ),
    ]
