# Generated by Django 3.2.6 on 2022-01-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frota', '0009_delete_corrida'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrotaPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver_veiculo', models.BooleanField(default=False)),
                ('ver_manutencao', models.BooleanField(default=False)),
                ('ver_despesa', models.BooleanField(default=False)),
                ('ver_relatorio', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frota"."frota_permissao',
            },
        ),
    ]
