# Generated by Django 3.2 on 2022-01-11 18:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frota', '0009_delete_corrida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculoabastecimento',
            name='combustivel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina'), ('Álcool', 'Álcool'), ('Gasolina/Álcool', 'Gasolina/Álcool')], max_length=40),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manutencao', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva')], max_length=40)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=40)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo')),
            ],
            options={
                'db_table': 'frota"."manutencao',
            },
        ),
    ]
