# Generated by Django 3.2 on 2022-01-14 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0010_auto_20220111_1541'),
        ('frota', '0011_auto_20220107_1143'),
    ]

    operations = [
    ]
