# Generated by Django 3.2 on 2022-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0012_merge_0010_auto_20220111_1541_0011_auto_20220107_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='frotapermissao',
            name='ver_abastecimento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='frotapermissao',
            name='ver_viagemlist',
            field=models.BooleanField(default=True),
        ),
    ]
