# Generated by Django 3.2 on 2022-01-26 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0014_alter_veiculoabastecimento_combustivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina'), ('Álcool', 'Álcool')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo'),
        ),
        migrations.DeleteModel(
            name='VeiculoAbastecimento',
        ),
    ]
