# Generated by Django 3.2 on 2022-01-26 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0015_auto_20220126_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='combustivel',
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='combustivel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasolina', 'Gasolina'), ('Álcool', 'Álcool')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
