# Generated by Django 3.2 on 2022-01-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211229_1000'),
        ('frota', '0016_auto_20220126_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viagem',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pessoa'),
        ),
        migrations.DeleteModel(
            name='Motorista',
        ),
    ]
