# Generated by Django 3.2 on 2022-01-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0018_alter_abastecimento_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frota.veiculo'),
        ),
    ]
