# Generated by Django 3.2.6 on 2022-02-09 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211229_1000'),
        ('frota', '0019_alter_abastecimento_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=20)),
                ('nome', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.pessoa')),
            ],
            options={
                'db_table': 'frota"."motorista',
            },
        ),
    ]
