# Generated by Django 3.2.6 on 2022-02-10 16:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0020_motorista'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(check=models.Q(('data_final__gte', django.db.models.expressions.F('data_inicial'))), name='datafinal_menor_datainicial'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.CheckConstraint(check=models.Q(('km_final__gt', django.db.models.expressions.F('km_inicial'))), name='kmfinal_menor_kminicial'),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.UniqueConstraint(condition=models.Q(('data_final', None)), fields=('veiculo',), name='Veiculo-emUso'),
        ),
    ]
