# Generated by Django 3.2.6 on 2022-02-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20211229_1000'),
        ('frota', '0021_auto_20220210_1353'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viagem',
            name='Veiculo-emUso',
        ),
        migrations.AddField(
            model_name='viagem',
            name='ajudante',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ajudante', to='core.pessoa'),
        ),
        migrations.AddField(
            model_name='viagem',
            name='motorista2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motorista2', to='core.pessoa'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='destino',
            field=models.CharField(max_length=250),
        ),
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.UniqueConstraint(condition=models.Q(('data_final', None)), fields=('veiculo',), name='Veiculo Em Uso'),
        ),
    ]
