# Generated by Django 3.2.6 on 2022-03-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0023_auto_20220222_1653'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='viagem',
            constraint=models.UniqueConstraint(fields=('veiculo', 'data_inicial', 'hora_inicial'), name='Ja Reservado para esta data,verificar os horarios'),
        ),
    ]
