# Generated by Django 3.2.6 on 2022-03-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0024_viagem_ja reservado para esta data,verificar os horarios'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='viagem',
            name='Veiculo Em Uso',
        ),
        migrations.AddField(
            model_name='viagem',
            name='tipo',
            field=models.CharField(choices=[('Manutençao', 'Manutenção'), ('Viagem', 'Viagem')], default='Viagem', max_length=40),
        ),
    ]
