# Generated by Django 3.2.6 on 2022-03-10 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Calendário',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18, unique=True)),
                ('interno', models.BooleanField(default=True)),
                ('capacidade', models.IntegerField()),
                ('linha', models.CharField(choices=[('Leve', 'Leve'), ('Pesada', 'Pesada'), ('Pesada Modinha', 'Pesada Modinha')], max_length=20, null=True)),
                ('nick_spi', models.CharField(blank=True, max_length=20, null=True)),
                ('score', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True)),
                ('padrao', models.BooleanField(default=False, verbose_name='Padrão')),
                ('calendario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roupa.calendario')),
            ],
        ),
        migrations.CreateModel(
            name='PCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcp', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
                ('ordem_esperada', models.IntegerField()),
                ('recorrente', models.BooleanField(default=False)),
                ('status_spi', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcp', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RoupaBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('user_nome', models.CharField(max_length=30)),
                ('lavanderia', models.BooleanField(default=False)),
                ('expedicao', models.BooleanField(default=False)),
                ('geral', models.BooleanField(default=False)),
                ('frota', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('costura', models.ManyToManyField(blank=True, to='roupa.Etapa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacre', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacre', models.IntegerField(unique=True)),
                ('tag', models.ManyToManyField(blank=True, to='roupa.TAG')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.processo'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tag',
            field=models.ManyToManyField(blank=True, to='roupa.TAG'),
        ),
        migrations.CreateModel(
            name='DiasCalendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.calendario')),
            ],
        ),
    ]
