# Generated by Django 3.0.7 on 2021-06-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Calendário',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
                ('interno', models.BooleanField(default=True)),
                ('ordem_esperada', models.IntegerField()),
                ('recorrente', models.BooleanField(default=False)),
                ('status_spi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
                ('capacidade', models.IntegerField()),
                ('nick_spi', models.CharField(blank=True, max_length=20, null=True)),
                ('calendario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roupa.Calendario')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.Processo')),
            ],
        ),
        migrations.CreateModel(
            name='DiasCalendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.Calendario')),
            ],
        ),
    ]
