# Generated by Django 3.2.6 on 2022-03-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCorte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacre', models.IntegerField()),
                ('ficha_corte', models.CharField(blank=True, max_length=7, null=True)),
                ('dados', models.JSONField()),
            ],
        ),
    ]
