# Generated by Django 3.0.7 on 2021-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='interno',
        ),
        migrations.AddField(
            model_name='etapa',
            name='interno',
            field=models.BooleanField(default=True),
        ),
    ]
