# Generated by Django 3.0.7 on 2021-06-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0002_auto_20210606_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='linha',
            field=models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Pesada', 'Pesada'), ('Pesada Modinha', 'Pesada Modinha')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etapa',
            name='tag',
            field=models.ManyToManyField(blank=True, to='roupa.TAG'),
        ),
    ]
