# Generated by Django 3.0.7 on 2021-06-30 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0003_auto_20210628_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacre', models.IntegerField(unique=True)),
                ('tag', models.ManyToManyField(blank=True, to='roupa.TAG')),
            ],
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField()),
                ('entrada', models.DateField()),
                ('saida', models.DateField()),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roupa.Etapa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.Pedido')),
            ],
        ),
    ]
