# Generated by Django 3.0.7 on 2021-07-01 01:33

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0004_pedido_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', jsonfield.fields.JSONField()),
            ],
        ),
    ]
