# Generated by Django 3.0.7 on 2021-07-06 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0005_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='score',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='calendario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roupa.Calendario'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='linha',
            field=models.CharField(choices=[('Leve', 'Leve'), ('Pesada', 'Pesada'), ('Pesada Modinha', 'Pesada Modinha')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nome',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
