# Generated by Django 3.1.13 on 2021-07-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0005_api'),
    ]

    operations = [
        
    ]
