# Generated by Django 3.0.7 on 2021-07-08 23:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0006_auto_20210706_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='pcp',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Programacao',
        ),
    ]
