# Generated by Django 3.0.7 on 2021-07-09 00:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0007_auto_20210708_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='pcp',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
