# Generated by Django 3.1.13 on 2021-07-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0008_auto_20210708_2119'),
        ('roupa', '0006_auto_20210712_1059'),
    ]

    operations = [
    ]
