# Generated by Django 3.0.7 on 2021-08-10 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roupa', '0009_merge_20210719_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcp', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='api',
            name='pcp',
        ),
        migrations.CreateModel(
            name='PedidoTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roupa.Pedido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
