# Generated by Django 3.2.6 on 2021-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0011_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidotrack',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedidotrack',
            name='lacre',
            field=models.IntegerField(default=0),
        ),
    ]
