# Generated by Django 3.1.13 on 2021-09-25 13:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roupa', '0012_auto_20210913_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
