# Generated by Django 3.2.6 on 2021-10-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0016_auto_20210927_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoupaBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('user_nome', models.CharField(max_length=30)),
                ('lavanderia', models.BooleanField(default=False)),
                ('expedicao', models.BooleanField(default=False)),
                ('geral', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('costura', models.ManyToManyField(blank=True, to='roupa.Etapa')),
            ],
        ),
    ]
