# Generated by Django 3.2.6 on 2021-10-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0017_roupabot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEtapa',
        ),
    ]
