# Generated by Django 3.2.6 on 2021-10-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0019_roupabot_user2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roupabot',
            old_name='user2',
            new_name='usuario',
        ),
    ]
