# Generated by Django 3.2.6 on 2022-01-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roupa', '0020_rename_user2_roupabot_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roupabot',
            name='user_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
