# Generated by Django 3.0.7 on 2020-12-19 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20201219_0919'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=110)),
                ('origem', models.CharField(choices=[('Compra', 'Compra'), ('Fiação', 'Fiação'), ('Entrelaçadeira', 'Entrelaçadeira'), ('Tingimento', 'Tingimento')], max_length=20)),
                ('tipo', models.CharField(choices=[('Insumo', 'Insumo'), ('Material', 'Material')], max_length=20)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='ValorCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Material')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
            ],
            options={
                'verbose_name_plural': 'Valor de Compra',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, choices=[('kg', 'kg'), ('m', 'm')], max_length=20)),
                ('quantidade', models.FloatField()),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Material')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
            options={
                'verbose_name_plural': 'Produção',
            },
        ),
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, choices=[('kg', 'kg'), ('m', 'm')], max_length=20)),
                ('abertura_cardas', models.FloatField(blank=True)),
                ('conicaleira', models.FloatField(blank=True)),
                ('encolhimento', models.FloatField(blank=True)),
                ('estopa', models.FloatField(blank=True)),
                ('retalho', models.FloatField(blank=True)),
                ('retrabalho', models.FloatField(blank=True)),
                ('varredura', models.FloatField(blank=True)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Desempenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(blank=True, choices=[('kg', 'kg'), ('m', 'm')], max_length=20)),
                ('capacidade_total', models.IntegerField(blank=True, verbose_name='Capacidade Total')),
                ('dias_trabalhados', models.FloatField(blank=True, verbose_name='Dias Trabalhados')),
                ('total_planejado', models.IntegerField(blank=True, verbose_name='Total Planejado')),
                ('headcount', models.FloatField(blank=True, verbose_name='nº Colaboradores')),
                ('expedidores', models.FloatField(blank=True, verbose_name='nº Expedidores')),
                ('revisores', models.FloatField(blank=True, verbose_name='nº Revisores')),
                ('setup', models.TimeField(blank=True)),
                ('carga_descarga', models.TimeField(blank=True)),
                ('manutencao_corretiva', models.TimeField(blank=True)),
                ('manutencao_preventiva', models.TimeField(blank=True)),
                ('total_alvejado', models.FloatField(blank=True, verbose_name='Total Alvejado')),
                ('total_chamuscado', models.FloatField(blank=True, verbose_name='Total Chamuscado')),
                ('total_expedido', models.FloatField(blank=True, verbose_name='Total Expedido')),
                ('total_tingido', models.FloatField(blank=True, verbose_name='Total Expedido')),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
            options={
                'verbose_name_plural': 'Desempenho',
            },
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia', models.FloatField(blank=True)),
                ('laboratorio', models.FloatField(blank=True)),
                ('manutencao', models.FloatField(blank=True)),
                ('mao_de_obra', models.FloatField(blank=True)),
                ('material_uso_continuo', models.FloatField(blank=True)),
                ('vapor', models.FloatField(blank=True)),
                ('agua', models.FloatField(blank=True)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Material')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Setor')),
            ],
            options={
                'verbose_name_plural': 'Consumo',
            },
        ),
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composicao', models.FloatField()),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='produto.Material')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='produto.Material')),
            ],
            options={
                'verbose_name_plural': 'Composição',
            },
        ),
    ]
