# Generated by Django 3.0.7 on 2020-12-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenho',
            name='carga_descarga',
        ),
        migrations.RemoveField(
            model_name='desempenho',
            name='manutencao_corretiva',
        ),
        migrations.RemoveField(
            model_name='desempenho',
            name='manutencao_preventiva',
        ),
        migrations.RemoveField(
            model_name='desempenho',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='abertura_cardas',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='conicaleira',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='encolhimento',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='estopa',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='retalho',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='retrabalho',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='perda',
            name='varredura',
        ),
        migrations.RemoveField(
            model_name='producao',
            name='unidade',
        ),
        migrations.AddField(
            model_name='desempenho',
            name='total_recebido',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Recebido'),
        ),
        migrations.AddField(
            model_name='material',
            name='unidade',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('m', 'm')], max_length=20),
        ),
        migrations.AddField(
            model_name='perda',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produto.Material'),
        ),
        migrations.AddField(
            model_name='perda',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='origem',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Fiação', 'Fiação'), ('Entrelaçadeira', 'Entrelaçadeira'), ('Tingimento', 'Tingimento'), ('Tecelagem', 'Tecelagem'), ('Urdideira', 'Urdideira'), ('Perda', 'Perda')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('Insumo', 'Insumo'), ('Material', 'Material'), ('Refugo', 'Refugo')], max_length=20),
        ),
    ]
