# Generated by Django 3.0.7 on 2020-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20201222_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempenho',
            name='carga_descarga',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='manutencao_corretiva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='manutencao_preventiva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desempenho',
            name='setup',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
