# Generated by Django 3.0.7 on 2020-12-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20201222_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='quantidade',
            field=models.FloatField(default=0),
        ),
    ]
