# Generated by Django 3.0.7 on 2020-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_consumo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='inativo',
            field=models.BooleanField(default=False),
        ),
    ]
