# Generated by Django 3.0.7 on 2021-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20201231_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='expedidores',
            field=models.FloatField(blank=True, null=True, verbose_name='nº Expedidores'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='revisores',
            field=models.FloatField(blank=True, null=True, verbose_name='nº Revisores'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='total_alvejado',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Alvejado'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='total_chamuscado',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Chamuscado'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='total_expedido',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Expedido'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='total_tingido',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Tingido'),
        ),
    ]
