# Generated by Django 3.0.7 on 2021-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20210103_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='dias_trabalhados',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias Trabalhados'),
        ),
    ]
