# Generated by Django 3.0.7 on 2021-01-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20210103_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desempenho',
            name='unidade',
        ),
    ]
