# Generated by Django 3.0.7 on 2021-01-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_remove_desempenho_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempenho',
            name='tempo_total_atendimento',
            field=models.FloatField(blank=True, null=True, verbose_name='Tempo Total de Atendimento'),
        ),
    ]
