# Generated by Django 3.0.7 on 2021-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_desempenho_tempo_total_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='capacidade_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidade Total'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='headcount',
            field=models.FloatField(blank=True, null=True, verbose_name='nº Colaboradores'),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='total_planejado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Planejado'),
        ),
    ]
