# Generated by Django 3.0.7 on 2021-08-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_auto_20210306_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='custo',
            name='patrimonio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
