# Generated by Django 3.2.6 on 2022-03-10 23:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cota_mensal', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Comercial',
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='Descrição')),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('data_entrega', models.DateField(blank=True, verbose_name='Entrega Pedido')),
                ('notas', models.CharField(blank=True, max_length=140, null=True)),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberta', max_length=50, verbose_name='Situação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.cliente')),
                ('representante', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cotações',
            },
        ),
        migrations.CreateModel(
            name='CustoManipulacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=140)),
                ('custo', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cliente')),
            ],
            options={
                'verbose_name_plural': 'Custo Manipulações',
            },
        ),
        migrations.CreateModel(
            name='ItemCotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_cliente', models.CharField(blank=True, max_length=10)),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(blank=True)),
                ('target', models.FloatField(blank=True)),
                ('data_entrega', models.DateField(blank=True, verbose_name='Entrega')),
                ('notas', models.CharField(blank=True, max_length=140, null=True)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.cotacao')),
            ],
            options={
                'verbose_name_plural': 'Itens Cotações',
            },
        ),
        migrations.CreateModel(
            name='PontuacaoProducao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(unique=True, verbose_name='Pontuação')),
                ('valor_interno', models.FloatField()),
                ('valor_externo', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Pontuação Produção',
            },
        ),
        migrations.CreateModel(
            name='Tecido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, unique=True)),
                ('composicao', models.CharField(max_length=140, verbose_name='Composição')),
                ('peso', models.FloatField()),
                ('inativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo', models.FloatField()),
                ('lavanderia', models.FloatField()),
                ('acabamento', models.FloatField()),
                ('insumos', models.FloatField()),
                ('operacional', models.FloatField()),
                ('tributos', models.FloatField()),
                ('total', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.itemcotacao')),
                ('manipulacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.customanipulacao')),
                ('pontos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pontuacaoproducao')),
                ('tecido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.tecido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('ref', models.IntegerField()),
                ('consumo', models.FloatField()),
                ('lavanderia', models.FloatField()),
                ('acabamento', models.FloatField()),
                ('insumos', models.FloatField()),
                ('pontos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.pontuacaoproducao')),
                ('tecido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comercial.tecido')),
            ],
        ),
        migrations.CreateModel(
            name='PrecoTecido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('valor_consumo', models.FloatField()),
                ('valor_venda', models.FloatField()),
                ('tecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.tecido')),
            ],
            options={
                'verbose_name_plural': 'Preço Tecidos',
            },
        ),
        migrations.AddField(
            model_name='itemcotacao',
            name='produto',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='comercial.produto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='comercial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.comercial'),
        ),
    ]
