# Generated by Django 3.0.7 on 2021-03-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=18)),
            ],
            options={
                'verbose_name_plural': 'Comercial',
            },
        ),
    ]
