# Generated by Django 3.2.6 on 2022-03-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='nome',
            field=models.CharField(choices=[('PCP', 'PCP'), ('Qualidade', 'Qualidade'), ('Frota', 'Frota')], default='PCP', max_length=20),
        ),
    ]
