# Generated by Django 3.0.7 on 2020-12-18 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name_plural': 'Setores'},
        ),
    ]
