# Generated by Django 3.2.6 on 2022-03-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('compras_fornecedor_id', models.IntegerField(db_column='compras_fornecedor_id', null=True)),
                ('endereco', models.CharField(db_column='endereco', max_length=80)),
                ('bairro', models.CharField(db_column='bairro', max_length=45)),
                ('numero', models.CharField(db_column='numero', max_length=40)),
                ('cidade', models.CharField(db_column='cidade', max_length=45)),
                ('uf', models.CharField(db_column='uf', max_length=2)),
                ('cep', models.CharField(db_column='cep', max_length=8)),
                ('created_at', models.DateTimeField(db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'frota"."enderecos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoViagem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('endereco_id', models.IntegerField(db_column='endereco_id')),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('compras_pedido_id', models.IntegerField(db_column='compras_pedido_id', null=True)),
                ('data_prevista', models.DateField(db_column='data_prevista')),
                ('tipo', models.CharField(db_column='tipo', max_length=1)),
                ('origem', models.CharField(db_column='origem', max_length=1)),
                ('situacao', models.CharField(db_column='situacao', max_length=1)),
                ('prioridade', models.CharField(db_column='prioridade', max_length=1)),
                ('peso', models.FloatField(db_column='peso')),
                ('data_solicitacao', models.DateTimeField(db_column='data_solicitacao')),
                ('data_atendimento', models.DateTimeField(db_column='data_atendimento', null=True)),
                ('data_finalizacao', models.DateTimeField(db_column='data_finalizacao', null=True)),
            ],
            options={
                'db_table': 'frota"."viagem_solicitacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCompras',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=45)),
            ],
            options={
                'db_table': 'souzacambos"."users',
                'managed': False,
            },
        ),
    ]
