# Generated by Django 3.2.6 on 2022-03-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bot_nome'),
        ('core', '0002_enderecos_solicitacaoviagem_usercompras'),
    ]

    operations = [
    ]
