# Generated by Django 3.2.6 on 2022-03-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20220321_0813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitacaoViagem',
        ),
    ]
