# Generated by Django 3.0.7 on 2020-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201219_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='nome',
            field=models.CharField(default='-', max_length=18),
        ),
    ]
