# Generated by Django 3.0.7 on 2021-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_periodo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comercial',
            field=models.CharField(blank=True, choices=[('Mendes Júnior', 'Mendes Júnior'), ('Xavantes', 'Xavantes'), ('Cotton Move', 'Cotton Move')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='industrial',
            field=models.BooleanField(default=False),
        ),
    ]
