# Generated by Django 3.2.6 on 2022-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_solicitacaoviagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetoresPortal',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='nome', max_length=80)),
            ],
            options={
                'db_table': 'souzacambos"."setores',
                'managed': False,
            },
        ),
    ]
