# Generated by Django 3.0.7 on 2021-03-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210306_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comercial',
        ),
    ]
