# Generated by Django 3.0.7 on 2021-03-06 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        ('core', '0007_remove_user_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comercial.Comercial'),
        ),
    ]
