# Generated by Django 3.0.7 on 2021-03-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        ('core', '0008_user_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comercial',
        ),
        migrations.AddField(
            model_name='user',
            name='comercial',
            field=models.ManyToManyField(to='comercial.Comercial'),
        ),
    ]
