# Generated by Django 3.0.7 on 2021-05-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210306_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='industrial',
            new_name='confeccao',
        ),
        migrations.AddField(
            model_name='user',
            name='textil',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setor',
            name='divisao',
            field=models.CharField(choices=[('Têxtil', 'Têxtil'), ('Confecção', 'Confecção'), ('Geral', 'Geral')], max_length=20, verbose_name='Divisão'),
        ),
    ]
