# Generated by Django 3.0.7 on 2021-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='token',
            field=models.CharField(max_length=46),
        ),
    ]
