# Generated by Django 3.0.7 on 2021-05-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bot_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACABAMENTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OFICINA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=154, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_nome', models.CharField(max_length=30)),
                ('user_tel', models.CharField(max_length=30)),
                ('lavanderia', models.BooleanField(default=False)),
                ('corte', models.BooleanField(default=False)),
                ('expedicao', models.BooleanField(default=False)),
                ('acabamento', models.ManyToManyField(to='core.ACABAMENTO')),
                ('oficina', models.ManyToManyField(to='core.OFICINA')),
            ],
        ),
    ]
