# Generated by Django 3.0.7 on 2021-05-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210517_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbot',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
