# Generated by Django 3.0.7 on 2021-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210517_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbot',
            name='geral',
            field=models.BooleanField(default=False),
        ),
    ]
