# Generated by Django 3.0.7 on 2021-07-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userbot_geral'),
    ]

    operations = [
       
    ]
