# Generated by Django 3.1.13 on 2021-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userbot_geral'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='divisao',
            field=models.CharField(choices=[('Oficinas Internas', 'Oficinas Internas'), ('Oficinas Externas', 'Oficinas Externas')], default=2, max_length=20, verbose_name='Divisão'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oficina',
            name='choice',
            field=models.CharField(max_length=154, unique=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
