# Generated by Django 3.1.13 on 2021-07-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userbot_geral'),
    ]

    operations = [
        
    ]
