# Generated by Django 3.1.13 on 2021-07-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210712_1059'),
        ('core', '0019_auto_20210706_2024'),
    ]

    operations = [
    ]
