# Generated by Django 3.1.13 on 2021-07-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210726_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='choice',
            field=models.CharField(max_length=154, unique=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
