# Generated by Django 3.0.7 on 2021-08-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210726_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='last_update_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bot',
            name='minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userbot',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='choice',
            field=models.CharField(max_length=154, unique=True, verbose_name='Oficina'),
        ),
    ]
