# Generated by Django 3.1.13 on 2021-08-04 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210803_2132'),
        ('core', '0022_auto_20210727_0750'),
    ]

    operations = [
    ]
