# Generated by Django 3.2.6 on 2021-10-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210810_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comercial',
        ),
    ]
