# Generated by Django 3.2.6 on 2021-10-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_user_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_bot',
        ),
        migrations.DeleteModel(
            name='UserBot',
        ),
    ]
