# Generated by Django 3.2.6 on 2021-12-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211007_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(blank=True, db_column='nomecolaborador', max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'souzacambos"."colaboradors',
                'managed': False,
            },
        ),
    ]
