# Generated by Django 3.2.6 on 2021-12-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('descricao', models.CharField(blank=True, db_column='descricao', max_length=70, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'souzacambos"."compras_produtos',
                'managed': False,
            },
        ),
    ]
