# Generated by Django 3.2.6 on 2021-12-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_user_frota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACABAMENTO',
        ),
        migrations.DeleteModel(
            name='OFICINA',
        ),
    ]
